---
# ----------------------------------------------------------------#
#   ProjectClean  
#
# This playbook will remove all schedule tasks and related  
# files for the windows eventlog archive project. 
#         + Copy archived logs to server - Schedule Task
#         + Maintain archive event logs        
#         + UploadArchive.ps1 - Powershell script
#         + RemoveFiles.ps1 - Powershell script
#     win_shell: "{{ lookup('template', './CreateCSR.ps1') }}"    
# ----------------------------------------------------------------#
- name: Create a certificate request
  hosts: all
  gather_facts: true
 #vars:
 #  kyndryl_folder: 'C:\Kyndryl\'
 #  upload_file: 'UploadArchive.ps1'
 #  remove_file: 'RemoveFiles.ps1'

  tasks:
  # run the powershell script to create the request file  
    - name: "Run powershell to create request"
      win_shell: "{{ lookup('file', './CreateCSR.ps1') }}"  
      register: csr
    
  # Debug write out 
    - name: "Print the returned value"
      debug:
        msg: "{{ csr }}"
      run_once: true
      delegate_to: localhost 

  # Copy file to a remote location 
    - name: Copy csr file to remote host
      win_copy:
        src: 'C:\Kyndryl\CSR\'
        dest: '\\172.16.23.21\tmp'
        remote_src: yes
