---
# ----------------------------------------------------------------#
#   Run the Certreq  on work group servers
#
# 
# ----------------------------------------------------------------#
- name: Create a certificate request
  hosts: all
  gather_facts: true
  vars: 
    kyndryl_folder: 'C:\Kyndryl\'

  tasks:
    # Check for script folder 
    - name: Kyndryl folder check
      win_stat:
        path: "{{ kyndryl_folder }}"
      register: folder_check

    # Create script folder if it does not exist
    - name: Create directory structure if it does not exist
      win_file:
        path: "{{ kyndryl_folder }}"
        state: directory
      when: folder_check.stat.exists == false
    
    # Copy file to a remote location 
    - name: Copy powershell script to remote host
      win_copy:
        src: CreateCSR.ps1
        dest: "{{ kyndryl_folder }}CreateCSR.ps1"
      #delegate_to: localhost
    
  # Run the powershell script to create the request file  
    - name: "Run powershell to create request"
      win_shell: "{{ kyndryl_folder }}CreateCSR.ps1"  
        
  # Copy file to a remote location 
    - name: Copy folder contents recursively
      win_copy:
        src: "{{ kyndryl_folder }}"
        dest: /tmp/requestfile/
        remote_src: yes
   