---
# ----------------------------------------------------------------#
#   Enable certificates from the Domain
#
  
# ----------------------------------------------------------------#
- name: Create a certificate request
  hosts: all
  gather_facts: true


  tasks:
  # run the powershell script to create the request file  
    - name: "Run powershell to create request"
      win_shell: "{{ lookup('file', './CreateCSR.ps1') }}"  
      register: csr